export const GET_ALL_EMPLOYEE_REQUEST = 'GET_ALL_EMPLOYEE_REQUEST'
export const GET_ALL_EMPLOYEE_SUCCESS = 'GET_ALL_EMPLOYEE_SUCCESS'
export const GET_ALL_EMPLOYEE_FAIL = 'GET_ALL_EMPLOYEE_FAIL'
export const GET_SINGLE_EMPLOYEE_REQUEST = 'GET_SINGLE_EMPLOYEE_REQUEST'
export const GET_SINGLE_EMPLOYEE_SUCCESS = 'GET_SINGLE_EMPLOYEE_SUCCESS'
export const GET_SINGLE_EMPLOYEE_FAIL = 'GET_SINGLE_EMPLOYEE_FAIL'

export const EMPLOYEE_ADD_REQUEST = 'EMPLOYEE_ADD_REQUEST'
export const EMPLOYEE_ADD_SUCCESS = 'EMPLOYEE_ADD_SUCCESS'
export const EMPLOYEE_ADD_FAIL = 'EMPLOYEE_ADD_FAIL'

export const EMPLOYEE_EDIT_REQUEST = 'EMPLOYEE_EDIT_REQUEST'
export const EMPLOYEE_EDIT_SUCCESS = 'EMPLOYEE_EDIT_SUCCESS'
export const EMPLOYEE_EDIT_FAIL = 'EMPLOYEE_EDIT_FAIL'

export const EMPLOYEE_DELETE_REQUEST = 'EMPLOYEE_DELETE_REQUEST'
export const EMPLOYEE_DELETE_SUCCESS = 'EMPLOYEE_DELETE_SUCCESS'
export const EMPLOYEE_DELETE_FAIL = 'EMPLOYEE_DELETE_FAIL'
